# Generated by Django 4.1.7 on 2023-02-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storytime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-pk']},
        ),
    ]
